- name: Install zsh
  become: yes
  apt:
    name: zsh
    state: present
- name: Get the full path of Zsh
  become: yes
  shell: which zsh
  register: zsh_path
- name: Set Zsh as the default shell
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_path.stdout }}"
