- name: Install development tools and libraries
  become: yes
  apt:
    name:
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - curl
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    state: present
- name: Install asdf Python plugin
  shell: |
    . "{{ ansible_env.HOME }}/.asdf/asdf.sh"
    asdf plugin add python
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"
- name: Install Python
  shell: |
    . "{{ ansible_env.HOME }}/.asdf/asdf.sh"
    asdf install python 3.12.0
    asdf global python 3.12.0
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"
