- name: Install asdf terraform plugin
  shell: |
    . "{{ ansible_env.HOME }}/.asdf/asdf.sh"
    asdf plugin add terraform
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"
- name: Install terraform
  shell: |
    . "{{ ansible_env.HOME }}/.asdf/asdf.sh"
    asdf install terraform 1.6.4
    asdf global terraform 1.6.4
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"
- name: Install asdf awscli plugin
  shell: |
    . "{{ ansible_env.HOME }}/.asdf/asdf.sh"
    asdf plugin add awscli
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"
- name: Install awscli
  shell: |
    . "{{ ansible_env.HOME }}/.asdf/asdf.sh"
    asdf install awscli 2.13.38
    asdf global awscli 2.13.38
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"
- name: Install asdf gcloud plugin
  shell: |
    . "{{ ansible_env.HOME }}/.asdf/asdf.sh"
    asdf plugin add gcloud
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"
- name: Install gcloud
  shell: |
    . "{{ ansible_env.HOME }}/.asdf/asdf.sh"
    asdf install gcloud latest
    asdf global gcloud latest
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"
